name: check-formatting
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '18'
